services:
  game-web-server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: hello-phaser-dev
    ports:
      - "5173:5173"
    volumes:
      - ./webgame:/webgame
      - /webgame/node_modules
    stdin_open: true
    tty: true
